-- Run this in your Supabase SQL Editor

-- 1. Profiles Table (Syncs with Clerk ideally, or just created on the fly)
create table profiles (
  id uuid primary key default gen_random_uuid(),
  user_id text not null, -- Clerk User ID
  role text check (role in ('teacher', 'student')),
  full_name text,
  email text,
  created_at timestamp with time zone default now()
);

-- 2. Sessions (Classes)
create table sessions (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  teacher_id text not null, -- Clerk User ID
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- 3. Activity Logs (Focus Events)
create table activity_logs (
  id bigint generated by default as identity primary key,
  session_code text not null,
  student_name text not null, -- Storing name directly for simplicity in this demo
  event_type text check (event_type in ('FOCUS_LOST', 'FOCUS_GAINED', 'JOIN', 'LEAVE')),
  timestamp timestamp with time zone default now()
);

-- Enable RLS (Optional for now, but good practice)
alter table tables enable row level security;
-- For this demo, we might want to allow public insert if we don't setup full RLS policies yet
-- create policy "Enable insert for everyone" on activity_logs for insert with check (true);
