-- ⚠️ DESTRUCTIVE: Runs a full reset of your tables
-- Run this in Supabase SQL Editor to fix any schema mismatch issues

-- 1. DROP EXISTING TABLES (Reset)
DROP TABLE IF EXISTS quiz_responses;
DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS profiles;

-- 2. CREATE TABLES (Fresh Setup)

-- Activity Logs (Student Focus Detection)
create table activity_logs (
  id bigint generated by default as identity primary key,
  session_code text not null,
  student_name text not null,
  event_type text check (event_type in ('FOCUS_LOST', 'FOCUS_GAINED', 'JOIN', 'LEAVE')),
  timestamp timestamp with time zone default now()
);

-- Quiz Responses (Student Answers)
create table quiz_responses (
  id bigint generated by default as identity primary key,
  session_code text not null,
  student_name text not null,
  question text not null,
  answer_given text not null,
  is_correct boolean not null,
  timestamp timestamp with time zone default now()
);

-- Sessions (Classroom Management)
create table sessions (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  teacher_id text not null,
  is_active boolean default true,
  created_at timestamp with time zone default now()
);

-- Profiles (User Data)
create table profiles (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  role text check (role in ('teacher', 'student')),
  full_name text,
  email text,
  created_at timestamp with time zone default now()
);

-- 3. ENABLE SECURITY
alter table activity_logs enable row level security;
alter table quiz_responses enable row level security;
alter table sessions enable row level security;
alter table profiles enable row level security;

-- 4. OPEN ACCESS (For Demo Simplicity - Remove in Production)
create policy "Public Insert Activity" on activity_logs for insert with check (true);
create policy "Public Read Activity" on activity_logs for select using (true);

create policy "Public Insert Quiz" on quiz_responses for insert with check (true);
create policy "Public Read Quiz" on quiz_responses for select using (true);

create policy "Public Insert Sessions" on sessions for insert with check (true);
create policy "Public Read Sessions" on sessions for select using (true);

create policy "Public Insert Profiles" on profiles for insert with check (true);
create policy "Public Read Profiles" on profiles for select using (true);
